services:
  - type: web
    name: research-brief-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn src.api.server:app --host 0.0.0.0 --port 10000
    envVars:
      - key: MISTRAL_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: TAVILY_API_KEY
        sync: false
      - key: BRAVE_SEARCH_API_KEY
        sync: false
      - key: SERPAPI_API_KEY
        sync: false
      - key: LANGSMITH_API_KEY
        sync: false
      - key: LOG_LEVEL
        value: INFO